name: fieldframe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3
  url_launcher: ^6.1.11
  google_sign_in: ^6.1.5
  app_links: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^0.8.7+3
  permission_handler: ^11.3.1
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.2
  device_info_plus: ^10.1.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.0
  http_parser: ^4.0.2







# REMOVE THIS LINE: flutter_web_auth: ^0.5.0











flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # <- Path to your icon image (must be PNG)


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true



